[Interface]
Address    = fd00:2::1/64
ListenPort = 51820
PrivateKey = CGHgMUI6tbGNm7I+Z9j8rrmHStQo3ZmIc6CE++LJfUI=
PostUp   = ip6tables -A FORWARD -i wg0 -j ACCEPT
PostUp   = ip6tables -A FORWARD -o wg0 -j ACCEPT
PostUp   = ip6tables -A INPUT   -i wg0 -j ACCEPT
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT
PostDown = ip6tables -D FORWARD -o wg0 -j ACCEPT
PostDown = ip6tables -D INPUT   -i wg0 -j ACCEPT

[Peer]
# PC3 cliente
PublicKey           = 09ZJ3oZVF/TORXhyNQYX5H+POGWY46LHeE+B7xJMFwI=
AllowedIPs          = fd00:2::2/128
PersistentKeepalive = 25
