frr version 8.1
frr defaults traditional
hostname R1-Linux
log file /var/log/frr/frr.log
!
ipv6 forwarding
!
interface eth0
 description Red publica hacia R2 fa0/0
!
interface eth1
 description LAN interna hacia Switch1
!
router ospf6
 ospf6 router-id 1.1.1.1
 interface eth0 area 0.0.0.0
 interface eth1 area 0.0.0.0
!
line vty
!
